# Generated by Django 3.2.15 on 2022-09-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.CharField(choices=[('green', 'GREEN'), ('yellow', 'YELLOW'), ('orange', 'ORANGE'), ('red', 'RED'), ('black', 'BLACK')], default='green', max_length=6),
        ),
    ]
