# Generated by Django 3.2.15 on 2022-09-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='list',
            name='tags',
        ),
        migrations.AlterField(
            model_name='list',
            name='listno',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=1),
        ),
    ]
