# Generated by Django 3.2.15 on 2022-09-26 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20220921_0615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='created',
            new_name='createdon',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='createdon',
        ),
        migrations.RemoveField(
            model_name='list',
            name='listno',
        ),
        migrations.AddField(
            model_name='list',
            name='deletedon',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='updatedon',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='deletedon',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='updatedon',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
