# Generated by Django 3.2.15 on 2022-09-27 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_auto_20220926_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='createdon',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='updatedon',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='createdon',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='updatedon',
            new_name='updated_on',
        ),
        migrations.RemoveField(
            model_name='list',
            name='deletedon',
        ),
        migrations.RemoveField(
            model_name='list',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deletedon',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='list',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='list',
            name='deleted_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_requests_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='deleted_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_requests_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
