# Generated by Django 3.2.15 on 2022-09-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20220927_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='deleted_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deleted_on',
            field=models.DateTimeField(null=True),
        ),
    ]
