# Generated by Django 3.2.15 on 2022-09-28 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20220927_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='listno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.list'),
        ),
    ]
