# Generated by Django 3.2.15 on 2022-10-03 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_task_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tags',
            new_name='Priority',
        ),
    ]
