# Generated by Django 3.2.15 on 2022-10-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_tags_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Priority',
            field=models.CharField(choices=[('High', 'High'), ('Normal', 'Normal'), ('Low', 'Low')], default='Normal', max_length=9),
        ),
    ]
