# Generated by Django 3.2.15 on 2022-10-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_task_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Priority',
            new_name='priority',
        ),
    ]
