# Generated by Django 3.2.15 on 2022-10-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20221014_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='listno',
            new_name='list_no',
        ),
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
