# Generated by Django 3.2.15 on 2022-10-26 16:54

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=base.models.one_week_hence),
        ),
    ]
