# Generated by Django 3.2.15 on 2022-10-26 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_task_due_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete', 'due_date']},
        ),
    ]
